development:
  adapter: postgresql
  database: randombackground_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: randombackground_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: randombackground_production
  pool: 5
  timeout: 5000